### ISSUE TITLE
ldd: command not found

### ISSUE THREAD

**Issue by max614** [kyamagu/matlab-sqlite3-driver#12]
Hi!

Great work with the drivers! This is exactly what I have been looking for, so keep up the good work :)

I've got one issue though,

When I run 

`!ldd +sqlite3/private/libsqlite3_.mex*`

in the Matlab terminal I get the following response:

`/bin/bash: ldd: command not found`

Thus, I can't run `sqlite3.make` without crashing (locked by mexLock API.)

Do you have a solution to this? I've tried starting matlab by copying and pasting the preload line to the terminal but that didn't help.

I appreciate all the help I can get and I'm sure my issues are just a result of me being a complete idiot :)

Best,

Max

**Comment by kyamagu** [comment]
@max614 Are you using macOS? You have to use `otool -L` command instead of `ldd` on mac.

The other compile error could be related to [this](https://www.mathworks.com/matlabcentral/answers/315679-error-compilng-c-mex-file). Try restart Matlab first.

**Comment by max614** [comment]
Thank you so much! 

Now it works :)
