### ISSUE TITLE
Software versioning

### ISSUE THREAD

**Issue by ruimaciel** [kyamagu/matlab-sqlite3-driver#7]
HI,

First of all, thanks for your work.  Really great stuff.

Regarding your software, why not adopt a software versioning scheme?  It would benefit greatly those who are willing to adopt it but need to track upgrades and control possible compatibility issues.

**Comment by kyamagu** [comment]
@ruimaciel Thanks for the comments. I believe you noticed the releases, but feel free to post a comment on Github if you find any.

**Comment by ruimaciel** [comment]
@kyamagu  you were right, I've opened the issue before I'd noticed the releases section.

I have to say you've done an excellent job with this package.  Really great stuff.
